config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :quotes do
    resources :line_item_dates, except: %i[index show] do
      resources :line_items, except: %i[index show]
    end
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :line_item_date

  validates :name, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :unit_price, presence: true, numericality: { greater_than: 0 }

  delegate :quote, to: :line_item_date
end

app/models/line_item_date.rb
class LineItemDate < ApplicationRecord
  belongs_to :quote
  has_many :line_items, dependent: :destroy

  validates :date, presence: true, uniqueness: { scope: :quote_id }

  scope :ordered, -> { order(date: :asc) }

  def previous_date
    quote.line_item_dates.ordered.where("date < ?", date).last
  end
end

app/models/quote.rb
class Quote < ApplicationRecord
  has_many :line_item_dates, dependent: :destroy
  scope :ordered, -> { order(id: :desc) }
  
  validates :name, presence: true
  # after_create_commit -> { broadcast_prepend_to "quotes", partial: "quotes/quote", locals: { quote: self }, target: "quotes" }
  
  # after_create_commit -> { broadcast_prepend_later_to "quotes" }
  # after_update_commit -> { broadcast_replace_later_to "quotes" }
  # after_destroy_commit -> { broadcast_remove_to "quotes" }

  broadcasts_to -> (quote){ "quotes" }, inserts_by: :prepend
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/line_item_dates_controller.rb
class LineItemDatesController < ApplicationController
  before_action :set_quote
  before_action :set_line_item_date, only: %i[edit update destroy]

  def new
    @line_item_date = @quote.line_item_dates.build
  end

  def create
    @line_item_date = @quote.line_item_dates.build(line_item_date_params)

    if @line_item_date.save
      
      respond_to do |format|
        format.html { redirect_to quotes_path(@quote), notice: "Date was successfully created." }
        format.turbo_stream { flash.now[:notice] = "Date was successfully created."}
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @line_item_date.update(line_item_date_params)
      
      respond_to do |format|
        format.html { redirect_to quotes_path(@quote), notice: "Date updated successfully." }
        format.turbo_stream { flash.now[:notice] = "Date updated successfully." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @line_item_date.destroy

    respond_to do |format|
      format.html { redirect_to quotes_path(@quote), notice: "Date was successfully destroyed." }
      format.turbo_stream { flash.now[:notice] = "Date was successfully destroyed." }
    end
  end

  private

  def set_line_item_date
    @line_item_date = @quote.line_item_dates.find(params[:id])
  end

  def line_item_date_params
    params.require(:line_item_date).permit(:date)
  end

  def set_quote
    @quote = Quote.find(params[:quote_id])
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_quote
  before_action :set_line_item_date
  before_action :set_line_item, only: %i[edit update destroy]

  def new
    @line_item = @line_item_date.line_items.build
  end

  def create
    @line_item = @line_item_date.line_items.build(line_item_params)

    if @line_item.save
      
      respond_to do |format|
        format.html { redirect_to quote_path(@quote), notice: "Added item successfully." }
        format.turbo_stream { flash.now[:notice] = "Added item successfully." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @line_item.update(line_item_params)
      
      respond_to do |format|
        format.html { redirect_to quote_path(@quote), notice: "Updated successfully." }
        format.turbo_stream { flash.now[:notice] = "Updated successfully." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to quote_path(@quote), notice: "Line Item was successfully destroyed." }
      format.turbo_stream { flash.now[:notice] = "Line Item was successfully destroyed." }
    end
  end

  private

  def line_item_params
    params.require(:line_item).permit(:name, :quantity, :unit_price, :description)
  end

  def set_quote
    @quote = Quote.find(params[:quote_id])
  end

  def set_line_item_date
    @line_item_date = @quote.line_item_dates.find(params[:line_item_date_id])
  end

  def set_line_item
    @line_item = @line_item_date.line_items.find(params[:id])
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  def index
    @quotes = Quote.all.ordered
  end

  def show
    @line_item_dates = @quote.line_item_dates.includes(:line_items).ordered
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(quote_params)

    if @quote.save
      
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: "Quote successfully created!" }
        format.turbo_stream { flash.now[:notice] = "Quote successfully created!" }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @quote.update(quote_params)
      redirect_to quotes_path, notice: "Quote successfully updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @quote.destroy
    
    respond_to do |format|
      format.html { redirect_to quotes_path, notice: "Quote successfully destroyed!" }
      format.turbo_stream { flash.now[:notice] = "Quote successfully destroyed!" }
    end
  end

  private 

  def set_quote
    @quote = Quote.find_by(id: params[:id])
  end

  def quote_params
    params.require(:quote).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def render_turbo_stream_flash_messages
    turbo_stream.prepend "flash", partial: "layouts/flash"
  end

  def form_error_notification(object)
    if object.errors.any?
      tag.div class: "error-message" do
        object.errors.full_messages.to_sentence.capitalize
      end
    end
  end

  def nested_dom_id(*args)
    args.map { |arg| arg.respond_to?(:to_key) ? dom_id(arg) : arg }.join("_")
  end
end

app/helpers/line_item_dates_helper.rb
module LineItemDatesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div
    class="flash__message"
    data-controller="removals"
    data-action="animationend->removals#remove"
  >
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoteEditor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%# <div id="flash" class="flash">
      <%= render "layouts/flash" %>
    <%# </div>  %>
    <%= yield %>
  </body>
</html>

app/views/line_item_dates/_form.html.erb
<%= simple_form_for [quote, line_item_date], html: { class: "form line-item-date" } do |f| %>
  <%= form_error_notification(line_item_date) %>

  <%= f.input :date, html5: true, input_html: { autofocus: true } %>
  <%= link_to "Cancel", quote_path(quote), class: "btn btn--light" %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/line_item_dates/_line_item_date.html.erb
<%= turbo_frame_tag line_item_date do %>
  <div class="line-item-date">
    <%= turbo_frame_tag dom_id(line_item_date, :edit) do %>
      <div class="line-item-date__header">
        <h2 class="line-item-date__title">
          <%= l(line_item_date.date, format: :long) %>
        </h2>

        <div class="line-item-date__actions">
          <%= button_to "Delete",
                        [quote, line_item_date],
                        method: :delete,
                        form: { data: { turbo_confirm: "Are you sure?" } },
                        class: "btn btn--light" %>
          <%= link_to "Edit",
                      [:edit, quote, line_item_date],
                      class: "btn btn--light" %>
        </div>
      </div>
    <% end %>
    <div class="line-item-date__body">
      <div class="line-item line-item--header">
        <div class="line-item__name">Article</div>
        <div class="line-item__quantity">Quantity</div>
        <div class="line-item__price">Price</div>
        <div class="line-item__actions"></div>
      </div>

      <%= turbo_frame_tag nested_dom_id(line_item_date, "line_items") do %>
        <%= render line_item_date.line_items, quote: quote, line_item_date: line_item_date %>
      <% end %>
      <%= turbo_frame_tag nested_dom_id(line_item_date, LineItem.new) %>
      <div class="line-item-date__footer">
        <%= link_to "Add item",
                    [:new, quote, line_item_date, :line_item],
                    data: { turbo_frame: nested_dom_id(line_item_date, LineItem.new) },
                    class: "btn btn--primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/line_item_dates/create.turbo_stream.erb
<%= turbo_stream.update LineItemDate.new, "" %>

<% if previous_date = @line_item_date.previous_date %>
  <%= turbo_stream.after previous_date do %>
    <%= render @line_item_date, quote: @quote %>
  <% end %>
<% else %>
  <%= turbo_stream.prepend "line_item_dates" do %>
    <%= render @line_item_date, quote: @quote %>
  <% end %>
<% end %>

<%= render_turbo_stream_flash_messages %>

app/views/line_item_dates/destroy.turbo_stream.erb
<%= turbo_stream.remove @line_item_date %>
<%= render_turbo_stream_flash_messages %>

app/views/line_item_dates/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quote"), quote_path(@quote) %>

  <div class="header">
    <h1>Edit date</h1>
  </div>

  <%= turbo_frame_tag dom_id(@line_item_date, :edit) do %>
    <%= render "form", quote: @quote, line_item_date: @line_item_date %>
  <% end %>
</main>

app/views/line_item_dates/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quote"), quote_path(@quote) %>

  <div class="header">
    <h1>New date</h1>
  </div>

  <%= turbo_frame_tag @line_item_date do %>
    <%= render "form", quote: @quote, line_item_date: @line_item_date %>
  <% end %>
</main>

app/views/line_item_dates/update.turbo_stream.erb
<%= turbo_stream.remove @line_item_date %>

<% if previous_date = @line_item_date.previous_date %>
  <%= turbo_stream.after previous_date do %>
    <%= render @line_item_date, quote: @quote%>
  <% end %>
<% else %>
  <%= turbo_stream.prepend "line_item_dates" do %>
    <%= render @line_item_date, quote: @quote %>
  <% end %>
<% end %>

<%= render_turbo_stream_flash_messages %>

app/views/line_items/_form.html.erb
<%= simple_form_for [quote, line_item_date, line_item],
                    html: { class: "form line-item line-item--form" } do |f| %>

  <%= form_error_notification(line_item) %>

  <%= f.input :name,
              wrapper_html: { class: "line-item__name" },
              input_html: { autofocus: true } %>
  <%= f.input :quantity,
              wrapper_html: { class: "line-item__quantity" } %>
  <%= f.input :unit_price,
              wrapper_html: { class: "line-item__price" } %>
  <%= f.input :description,
              wrapper_html: { class: "line-item__description" } %>

  <div class="line-item__actions">
    <%= link_to "Cancel", quote_path(quote), class: "btn btn--light" %>
    <%= f.submit class: "btn btn--secondary" %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<%= turbo_frame_tag line_item do %>
  <div class="line-item">
    <div class="line-item__name">
      <%= line_item.name %>
      <div class="line-item__description">
        <%= simple_format line_item.description %>
      </div>
    </div>
    <div class="line-item__quantity-price">
      <%= line_item.quantity %>
      &times;
      <%= number_to_currency line_item.unit_price %>
    </div>
    <div class="line-item__quantity">
      <%= line_item.quantity %>
    </div>
    <div class="line-item__price">
      <%= number_to_currency line_item.unit_price %>
    </div>
    <div class="line-item__actions">
      <%= button_to "Delete",
                    [quote, line_item_date, line_item],
                    method: :delete,
                    class: "btn btn--light" %>
      <%= link_to "Edit",
                  [:edit, quote, line_item_date, line_item],
                  class: "btn btn--light" %>
    </div>
  </div>
<% end %>

app/views/line_items/create.turbo_stream.erb
<%= turbo_stream.update nested_dom_id(@line_item_date, LineItem.new), "" %>

<%= turbo_stream.append nested_dom_id(@line_item_date, "line_items") do %>
  <%= render @line_item, quote: @quote, line_item_date: @line_item_date %>
<% end %>

<%= render_turbo_stream_flash_messages %>

app/views/line_items/destroy.turbo_stream.erb
<%= turbo_stream.remove @line_item %>

app/views/line_items/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quote"), quote_path(@quote) %>

  <div class="header">
    <h1>Edit item</h1>
  </div>

  <%= turbo_frame_tag @line_item do %>
    <%= render "form",
             quote: @quote,
             line_item_date: @line_item_date,
             line_item: @line_item %>
  <% end %>
</main>

app/views/line_items/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quote"), quote_path(@quote) %>

  <div class="header">
    <h1>New item for <%= l(@line_item_date.date, format: :long) %></h1>
  </div>

  <%= turbo_frame_tag nested_dom_id(@line_item_date, LineItem.new) do %>
    <%= render "form",
             quote: @quote,
             line_item_date: @line_item_date,
             line_item: @line_item %>
  <% end %>
</main>

app/views/line_items/update.turbo_stream.erb
<%= turbo_stream.replace @line_item do %>
  <%= render @line_item, line_item_date: @line_item_date, quote: @quote %>
<% end %>

app/views/quotes/_form.html.erb
<%= simple_form_for quote, html: { class: "quote form" } do |f| %>
  <%= form_error_notification(quote) %>

  <%= f.input :name, input_html: { autofocus: true } %>
  <%= link_to "Cancel", quotes_path, class: "btn btn--light" %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/quotes/_quote.html.erb
<%= turbo_frame_tag quote do %>
  <div class="quote">
    <%= link_to quote.name, quote_path(quote), data: { turbo_frame: "_top" } %>
    <div class="quote__actions">
      <%= button_to "Delete",
                    quote_path(quote),
                    method: :delete,
                    class: "btn btn--light" %>
      <%= link_to "Edit",
                  edit_quote_path(quote),
                  class: "btn btn--light" %>
    </div>
  </div>
<% end %>

app/views/quotes/create.turbo_stream.erb
<%# <%= turbo_stream.prepend "quotes", partial: "quotes/quote", locals: { quote: @quote } %> 
<%= turbo_stream.prepend "quotes", @quote %>
<%= turbo_stream.update Quote.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove @quote %>
<%= render_turbo_stream_flash_messages %>

app/views/quotes/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quote"), quote_path(@quote) %>

  <div class="header">
    <h1>Edit quote</h1>
  </div>

  <%= turbo_frame_tag @quote do %>
    <%= render "form", quote: @quote %>
  <% end %>
</main>

app/views/quotes/index.html.erb
<%= turbo_stream_from "quotes" %>
<main class="container">
    <div class="header">
      <h1>Quotes</h1>
      <%= link_to "New quote", 
                    new_quote_path, 
                    class: "btn btn--primary",
                    data: { turbo_frame: dom_id(Quote.new) } %>
    </div>

  <%= turbo_frame_tag Quote.new %>
  <%= turbo_frame_tag "quotes" do %>
    <%= render @quotes %>
  <% end %>
</main>

app/views/quotes/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>

  <div class="header">
    <h1>New quote</h1>
  </div>

  <%= turbo_frame_tag @quote do %>
    <%= render "form", quote: @quote %>
  <% end %>
</main>

app/views/quotes/show.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
  <div class="header">
    <h1>
      <%= @quote&.name %>
    </h1>
    <%= link_to "New Date", new_quote_line_item_date_path(@quote), class: "btn btn--primary", data: { turbo_frame: dom_id(LineItemDate.new) } %>
  </div>
    <%= turbo_frame_tag dom_id(LineItemDate.new) %>
    <%= turbo_frame_tag "line_item_dates" do %>
      <%= render @line_item_dates, quote: @quote %>
    <% end %>
</main>